### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by wly0218** [wanygen/ThesisUESTC#1]
所有的章节都在一个文档中，不适合写硕博论文，应该用文件输入的形式，把各章节分开，这样管理起来更方便。参考文献也不能这样管理，应该用texbib文件管理。

**Comment by wanygen** [comment]
谢谢你的建议。各个部分分割成文件的话我在考虑，我自己是比较喜欢写成一个文件的，这个项目核心的工作是维护模板类和里面所包含的指令，至于使用者如何安排主文件应该给予充分的自由。给一个范例的本意是为了更好地解释这些指令的用法。

对bibtex的支持正在解决中，主要是现在缺少合适的.bst格式定义。之前那个项目里的定义其实也可以拿来用，只不过要先使用makeindex命令处理一下，不然就是提示函数未定义，这样的话就会依赖脚本进行编译，就像以前那个项目一样，我个人是不希望看到这样的结果的。如果有必要的话我会自己重新写一个。

我计划在0.2的版本里加入对bibtex的支持。分割文件的话如果大家都觉得方便也可以这样搞，但是即使这样也不会使用include这种危险的命令。LaTeX是有很多专门管理大型多文件项目的工具的。
