### ISSUE TITLE
cases公式第一行空白太大

### ISSUE THREAD

**Issue by wly0218** [wanygen/ThesisUESTC#10]
![default](https://user-images.githubusercontent.com/25203670/35338298-7f7ea690-0158-11e8-96ae-b623943cd467.png)
在矩阵前加花括号也有这样的问题

**Comment by wly0218** [comment]
![default](https://user-images.githubusercontent.com/25203670/35338795-cb912fd4-0159-11e8-93d7-39bc50a42a41.png)

**Comment by wanygen** [comment]
这个是mathspec宏包的问题，为了支持数学环境的Times New Roman字体。但是这个宏包貌似还不是太成熟。

**Comment by wly0218** [comment]
也就是暂时没有办法了？

**Comment by wanygen** [comment]
是的，除非不在数学环境中使用Times New Roman。

**Comment by garylavayou** [comment]
使用`singlespace`环境包围公式环境，参考[case brackets too big? [duplicate]
](https://tex.stackexchange.com/questions/362529/case-brackets-too-big) 和 [The curly brace is too big
](https://tex.stackexchange.com/questions/267146/the-curly-brace-is-too-big)。

我这么尝试了确实有用，但是不知道是否有办法在模板中进行统一的修改。 @x-magus @wly0218
