### ISSUE TITLE
关于参考文献的一个小问题

### ISSUE THREAD

**Issue by fantasua** [wanygen/ThesisUESTC#11]
模板很棒，用起来也很方便。
有这样一个小问题，main.tex里面导入参考文献用的 \thesisloadbibliography 命令，无法在texstudio中的文档结构视图中显示出参考文件项目，感觉这样在添加引用的时候不太方便。
请问怎样做可以解决这个问题呢？

**Comment by wanygen** [comment]
编辑器应该是检测的\bibliography命令，如果要照顾编辑器的习惯的话需要用\patchcmd修改这个命令的定义来适应学校的要求。我会考虑再更新的时候做这样的改进。

**Comment by wanygen** [comment]
已经更新过来了。

**Comment by ksnzh** [comment]
@wanygen 文献类型增加一下incollection吧

**Comment by fantasua** [comment]
那请问 \thesisloadbibliography 命令还需要在main.tex中删除吗？

**Comment by fantasua** [comment]
问题解决了，很完美。
谢谢大神！

**Comment by ksnzh** [comment]
@wanygen `@incollection` 类型对应于 GB/T 7714–2005 中所指的“专著中的析出文献”，算是书吧

**Comment by wly0218** [comment]
![default](https://user-images.githubusercontent.com/25203670/36059514-d524e784-0e74-11e8-8302-cbc4b8170481.png)

中文参考文献，作者超过三个后，应该显示等“”

**Comment by wanygen** [comment]
我记得格式要求没有要求这个啊

**Comment by wly0218** [comment]
这个是一个习惯性的，如果在中文中显示 et al.，属于中英文混排了

**Comment by wanygen** [comment]
混排就混排吧，反正中文也没什么好引用的。。

**Comment by wly0218** [comment]
如果能改最好还是改一下，虽然中文文献不多，但是有个别的还是要引用的

**Comment by wanygen** [comment]
搞个trick好了，把author那一项第三个人名字后面加个等，后面的截掉。
