### ISSUE TITLE
希望添加对程序代码的支持

### ISSUE THREAD

**Issue by armorunicorn** [wanygen/ThesisUESTC#12]
发现目标中不能直接添加程序代码，不知道能不能添加相关的支持

**Comment by wanygen** [comment]
什么目标啊？

**Comment by ksnzh** [comment]
https://stackoverflow.com/questions/3175105/writing-code-in-latex-document

2018-02-14 12:30 GMT+08:00 Wang Wen <notifications@github.com>:
