### ISSUE TITLE
缩略词表的格式如何解决

### ISSUE THREAD

**Issue by fantasua** [wanygen/ThesisUESTC#18]
论文的缩略词被评审老师要求修改格式，需要改成附件图中的格式
![tim 20180508170833](https://user-images.githubusercontent.com/3340180/39748378-82df26a8-52e2-11e8-965d-7a9564ed3d19.jpg)
请问如何才能实现这种格式呢

**Comment by fantasua** [comment]
那我需要修改模板文件的哪些部分呢

**Comment by wanygen** [comment]
评审老师疯了么，把格式说明甩她脸上。。标的修改后通过就不用改格式了，她自己估计也懒得检查，帮她省省心吧。
