### ISSUE TITLE
算法包的换行符失效

### ISSUE THREAD

**Issue by wyixiang** [wanygen/ThesisUESTC#19]
algorithm2e宏包的换行符是   \\;    ，但是这个模板并不识别这个命令，编译出来的结果也是没有自动换行的，这个图片是example.pdf中截出来的，学长有没有时间看一下这是什么原因
![2018-05-09 17 47 03](https://user-images.githubusercontent.com/21034627/39808420-7678412c-53b1-11e8-9545-14d2db74fa41.png)

**Comment by Lukeeeeee** [comment]
Same problem here. @wyixiang  Have you solved it?

**Comment by wyixiang** [comment]
No, but add a blank line can temporarily solve the problem.

**Comment by wanygen** [comment]
我也不太熟悉算法这个包，例子里面换行符好像工作没问题吧？

**Comment by wyixiang** [comment]
@wanygen 换行符起效的话编译出来应该是这样
![default](https://user-images.githubusercontent.com/21034627/41191542-d68d221e-6c23-11e8-9227-a57fd832127f.png)

**Comment by wanygen** [comment]
现在换行已经没问题了，谢谢你的意见！

**Comment by wyixiang** [comment]
谢谢学长，我把问题关闭了。
