### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by yiranjianning** [wanygen/ThesisUESTC#2]
texlive 2015,xelatex正常编译，无报错，但是生成的PDF中图片不显示。替换同名的png图片也一样不显示。
![qq 20170310114206](https://cloud.githubusercontent.com/assets/14798511/23781417/1fdcfcae-0588-11e7-8578-195d074676c8.png)

**Comment by wanygen** [comment]
这种情况没见过，光是这些信息也没法判断是哪里出了问题，要么你把你的代码发到我邮箱里帮你看看。

**Comment by yiranjianning** [comment]
又试了一下，自带的模板的pdf不显示，换成其它png或者其它pdf格式的是显示的。可能这个是由于模板自带的pdf版本或者来源有关吧。
不过这无关紧要了。
