### ISSUE TITLE
有子图时将会造成图目录出问题

### ISSUE THREAD

**Issue by NanerLee** [wanygen/ThesisUESTC#23]
按照论文标准，有子图的图标题，要将子图的标题按顺序写在总标题中
![image](https://user-images.githubusercontent.com/16791509/40605946-7363911e-6296-11e8-9f3b-e384515354d6.png)

但是这样的话图目录中就也会出现子图的标题。
![image](https://user-images.githubusercontent.com/16791509/40605990-89ee9302-6296-11e8-914e-7b9db4e2e572.png)

**Comment by wanygen** [comment]
是这样的，但这不是问题。

**Comment by NanerLee** [comment]
@wanygen 但是图目录中不是不应该出现子图的标题吗?

**Comment by wanygen** [comment]
格式说明没说不应该，就算出现也不是很难看。
