### ISSUE TITLE
subfig 宏包和 subfigure 宏包冲突。后者已过时，不建议使用。

### ISSUE THREAD

**Issue by yiranjianning** [wanygen/ThesisUESTC#3]
> subfig 宏包和 subfigure 宏包冲突。后者已过时，不建议使用。

想使用subfloat宏包时，需要subfig宏包，学校时富军学长的模板未提供该包，手动填加后与自带的subfigure冲突。详见讨论[http://bbs.ctex.org/forum.php?mod=viewthread&tid=150385&page=2#pid539801](url)

我看你这个模板也是subfigure宏包，是否可解决一下这种冲突呢？

**Comment by wanygen** [comment]
为什么一定要用subfloat，我觉得subfigure提供的功能是够用的。其实subfigure或者subfig都有点过时，好像比较新的包是subcaption。
