### ISSUE TITLE
正文里章节编号不显示

### ISSUE THREAD

**Issue by JosephChenHub** [wanygen/ThesisUESTC#4]
目录有“第一章 xxx"但是正文里没有编号显示，求助！

**Comment by wanygen** [comment]
什么叫没有编号显示？标题是在每一章首页居中显示的。

**Comment by JosephChenHub** [comment]
![1](https://cloud.githubusercontent.com/assets/22444830/25562657/d967eaae-2dbe-11e7-8147-fa4ff4962a4b.png) 图中没有编号

**Comment by JosephChenHub** [comment]
![2](https://cloud.githubusercontent.com/assets/22444830/25562661/eeb162fa-2dbe-11e7-9622-86571223b33a.png)
应该是这种形式

**Comment by JosephChenHub** [comment]
是不是加上“block"就可以了？\titleformat{\chapter}[block]
{\centering\fontsize{15pt}{15pt}\selectfont\heiti\thispagestyle{fancy}}{\thechapter}{7.5pt}{}

**Comment by wanygen** [comment]
直接编译样例没有发现这种问题啊？你是改了什么吗？

**Comment by JosephChenHub** [comment]
我添加了block才正常，我在ubuntu下直接编译就有这个问题




祝好
陈祖耀

在2017年04月30日 21:19，Wang Wen 写道：

直接编译样例没有发现这种问题啊？你是改了什么吗？

**Comment by wanygen** [comment]
没在ubuntu上测过，你用的什么版本的texlive？

**Comment by ksnzh** [comment]
@JosephChenHub Ubuntu 16.04下 Texlive 2015直=直接编译还有pdf图片不显示的问题。你有遇到吗？请问怎么解决呢？

**Comment by wanygen** [comment]
Issue#2里有说这种情况，他好像换换图片就行了。

**Comment by JosephChenHub** [comment]
PDF图片不显示可能是PDF的版本和图片PDF的版本不匹配
建议使用我GitHub上的那个微调过的模板，我17年本科论文OK




祝好
陈祖耀

在2018年01月15日 21:39，ksnzh 写道：

@JosephChenHub Ubuntu 16.04下 Texlive 2015直=直接编译还有pdf图片不显示的问题。你有遇到吗？请问怎么解决呢？

**Comment by wanygen** [comment]
刚刚更新替换掉了PDF图片，这样应该没有问题了。
