### ISSUE TITLE
Mac系统下字体问题

### ISSUE THREAD

**Issue by tinoryj** [wanygen/ThesisUESTC#6]

**Comment by tinoryj** [comment]
macOS下需要将SimSun替换为Songti TC，SimHei替换为Hei，否则会导致字体缺失

**Comment by wanygen** [comment]
好吧，我用ifplatform加个判断

**Comment by realleaf** [comment]
请问archlinux上也遇到该问题，该如何解决呢？字体不识别（确认系统有这些字体）

**Comment by x-magus** [comment]
linux的字体设置在54-62行。linux发行版的字体包很混乱，不知道哪个字体这个系统有那个系统没有的，都直接指定的字体文件。把字体文件拷到文档根目录下就行了。
