### ISSUE TITLE
公式间距问题

### ISSUE THREAD

**Issue by Pang-zhe** [wanygen/ThesisUESTC#7]
模板的公式段前段后距离较大，学校论文要求段前段后距离均为6磅

**Comment by wanygen** [comment]
学校的规定好难看= =

**Comment by Pang-zhe** [comment]
/(ㄒoㄒ)/~~如果想自己修改一下的话，在cls文件哪里编辑呢，谢谢学长

**Comment by wanygen** [comment]
最后几行吧，AtBeginDocument里面的四个命令，数值改成需要的就好了。
