### ISSUE TITLE
能不能添加缩略词索引

### ISSUE THREAD

**Issue by wly0218** [wanygen/ThesisUESTC#8]
能不能添加缩略词索引？怎么在cls中修改？谢谢！

**Comment by wanygen** [comment]
需要的话自己开一个无编号章节写一个tabular好了，反正学校对格式没什么要求。改cls有点麻烦。

**Comment by wanygen** [comment]
有时间的话加一下这个功能好了。

**Comment by wly0218** [comment]
中文中的格式应该如下：

逻辑卷管理器（Logical Volume Manager，LVM）

现在的模板显示的格式没有中文解释

![default](https://user-images.githubusercontent.com/25203670/35100132-978b99fe-fc95-11e7-976c-f95e96394b57.png)

**Comment by wanygen** [comment]
我改过来了……╮(￣▽￣"")╭

**Comment by wly0218** [comment]
嗯，已经测试，挺好！不过有个小的瑕疵，就是
![default](https://user-images.githubusercontent.com/25203670/35150649-239b5b94-fd56-11e7-95b7-9d2fd287f69c.png)


如果能修改为下面的形式就完美了

![default](https://user-images.githubusercontent.com/25203670/35150259-b70c2e0a-fd54-11e7-8de5-56bf341a50e5.png)

**Comment by wly0218** [comment]
![default](https://user-images.githubusercontent.com/25203670/35185518-d09d31ba-fe40-11e7-904d-c483128cb673.png)
![default](https://user-images.githubusercontent.com/25203670/35185544-23ef5924-fe41-11e7-9da7-6fcaa4be0be0.png)
![default](https://user-images.githubusercontent.com/25203670/35185552-571a7220-fe41-11e7-9045-0f0d54e1fe2e.png)
![default](https://user-images.githubusercontent.com/25203670/35185555-6630c93a-fe41-11e7-935d-a4428b8d0978.png)
缩写词之后多了一个空格，怎么处理？如果是在文中影响还不大，但是如果恰好在标点符号之前，影响还是挺大的。

**Comment by wanygen** [comment]
去掉空格以后更难看，想去的话后面加\ignorespaces命令。

**Comment by wly0218** [comment]
在什么地方加\ignorespaces命令？

**Comment by wanygen** [comment]
\gls后面

**Comment by wly0218** [comment]
那如果在cls文件中要修改什么地方？

**Comment by wanygen** [comment]
122行\glsentryshort{##1})后面吧。

**Comment by wly0218** [comment]
从第二次缩写开始怎么删除这个空客？

**Comment by wanygen** [comment]
124行\renewcommand*{\acronymentry}[1]{\acronymfont{\glsentryshort{##1}}}加在\acronymfont{\glsentryshort{##1}}后面试试。

**Comment by wly0218** [comment]
还是不行

**Comment by wanygen** [comment]
我重新定义了一下格式，现在应该可以了。

**Comment by wly0218** [comment]
![default](https://user-images.githubusercontent.com/25203670/35809550-016d1794-0ac4-11e8-8baa-0731497e6f30.png)
加了\gls之后运行出错，提示没有定义，实际上已经在导言区定义了

**Comment by wanygen** [comment]
原始的输出是什么啊，编辑器解析出来的不一定对。

**Comment by wanygen** [comment]
另外记得运行glossaries main这个明令禁止。

**Comment by wly0218** [comment]
\newacronym[description=逻辑卷管理器]{lvm}{LVM}{Logical Volume Manager}，直接拷贝的

**Comment by wly0218** [comment]
xelatex main就通不过

**Comment by wanygen** [comment]
又改了一下，应该没问题了= =||

**Comment by wly0218** [comment]
试了下缩略词表，太丑了

**Comment by wly0218** [comment]
如果能改进，就很好了
![img_20180211_170945](https://user-images.githubusercontent.com/25203670/36071854-4b229a36-0f50-11e8-8cec-35b9173fdbd5.jpg)

**Comment by wly0218** [comment]
如果能修改成这样的样式就非常好了

![default](https://user-images.githubusercontent.com/25203670/36072992-393caffa-0f64-11e8-8cee-6f47fa02d0f5.png)

**Comment by wanygen** [comment]
样式真的见仁见智了。。。
