### ISSUE TITLE
定理，定义等编号顺序不正确

### ISSUE THREAD

**Issue by wly0218** [wanygen/ThesisUESTC#9]
![default](https://user-images.githubusercontent.com/25203670/34993302-e92560ba-fb0a-11e7-9eaf-f306c4082d43.png)

应该是

定义 4.1;   定义 4.2；……

定理 4.1； 定理 4.2；……

各种类别别分编号

**Comment by wanygen** [comment]
你可以看一下专业的数学书，标号都是按这个方式编的。
![img_0104](https://user-images.githubusercontent.com/3732959/35022414-d4ebb868-fb70-11e7-87ad-91a33dac5fff.JPG)

**Comment by wly0218** [comment]
但是博士论文几乎都是单独编号的

**Comment by wly0218** [comment]
为了模板的通用性及易用性，建议修改cls

**Comment by wanygen** [comment]
不要跟着外行浪费生命，听我的没错的。只要没有明确要求就行。

**Comment by wly0218** [comment]
话虽如此，但是既然是模板，就应该按照使用人员(毕业生)的要求编写，尽量做到通用，已用，格式化。

**Comment by wanygen** [comment]
如果不同人的要求互相矛盾的话那就只能按我的喜好了。。。

**Comment by wly0218** [comment]
首先，值的肯定的是现在的模板已经很不错了，基本能满足大部分功能，但是对于写数学类博士论文还是有点瑕疵，如果目一章节的定理+引理+推论+注记等几十个或者上百个，现在的编号形式还是不容易识别，如果看可能，还是希望将这些不同了类别分别编号。

**Comment by wanygen** [comment]
非要这么搞的话把618-622行的[theorem]去掉就行了，有这一项是共享标号顺序。你是数学系的博士么？

**Comment by wly0218** [comment]
不是数学系的博士，不过用的数学公式比较多。
